arr1 = [CCGUCGUUGCGCUACAGC]
const adn = [
  { structure: 'UCU', result: "Sérine"},
  { structure: 'UCC', result: "Sérine"}, 
  { structure: 'UCA', result: "Sérine"},  
  { structure: 'UCG', result: "Sérine"}, 
  { structure: 'AGU', result: "Sérine"},
  { structure: 'AGC ', result: "Sérine"},
  { structure: 'CCU', result: "Proline"},
  { structure: 'CCC', result: "Proline"},
  { structure: 'CCA', result: "Proline"},
  { structure: 'CCG', result: "Proline"},
  { structure: 'UUA', result: "Leucine"},
  { structure: 'UUG', result: "Leucine"},
  { structure: 'UUU', result: "Phenylalaline"},
  { structure: 'UUC', result: "Phenylalaline"},
  { structure: 'CGU', result: "Arginine"},
  { structure: 'CGC', result: "Arginine"},
  { structure: 'CGA', result: "Arginine"},
  { structure: 'CGG', result: "Arginine"},
  { structure: 'AGA', result: "Arginine"},
  { structure: 'AGG', result: "Arginine"},
  { structure: 'UAU', result: "Tyrosine"},
  { structure: 'UAC', result: "Tyrosine"},
];
